export const CITIES = [
  'Abroad (out of India)',
  'Abohar',
  'Achalpur',
  'Adilabad',
  'Adityapur',
  'Adoni',
  'Agartala',
  'Agra',
  'Ahmadnagar',
  'Ahmedabad',
  'Aizawl',
  'Ajmer',
  'Akbarpur',
  'Akola',
  'Alandur',
  'Alappuzha',
  'Aligarh',
  'Allahabad',
  'Alwar',
  'Ambala',
  'Ambala Sadar',
  'Ambattur',
  'Ambernath',
  'Ambikapur',
  'Ambur',
  'Amravati',
  'Amreli',
  'Amritsar',
  'Amroha',
  'Anand',
  'Anantapur',
  'Anantnag',
  'Arrah',
  'Asansol',
  'Ashokenagar Kalyangarh',
  'Avadi',
  'Azamgarh',
  'Badalapur',
  'Bagaha',
  'Bagalkot',
  'Bahadurgarh',
  'Baharampur',
  'Bahraich',
  'Baidyabati',
  'Baleshwar',
  'Ballia',
  'Bally',
  'Bally Town',
  'Balurghat',
  'Banda',
  'Bangalore',
  'Bankura',
  'Bansberia',
  'Banswara',
  'Baran',
  'Baranagar',
  'Barasat',
  'Baraut',
  'Barddhaman',
  'Bareilly',
  'Baripada',
  'Barnala',
  'Barrackpur',
  'Barshi',
  'Basirhat',
  'Basti',
  'Batala',
  'Bathinda',
  'Beawar',
  'Begusarai',
  'Belgaum',
  'Bellary',
  'Bengaluru',
  'Bettiah',
  'Betul',
  'Bhadrak',
  'Bhadravati',
  'Bhadreswar',
  'Bhagalpur',
  'Bhalswa Jahangir Pur',
  'Bharatpur',
  'Bharuch',
  'Bhatpara',
  'Bhavnagar',
  'Bhilai Nagar',
  'Bhilwara',
  'Bhimavaram',
  'Bhind',
  'Bhiwadi',
  'Bhiwandi',
  'Bhiwani',
  'Bhopal',
  'Bhubaneswar',
  'Bhuj',
  'Bhusawal',
  'Bid',
  'Bidar',
  'Bidhan Nagar',
  'Biharsharif',
  'Bijapur',
  'Bikaner',
  'Bilaspur',
  'Boisar',
  'Bokaro Steel',
  'Bongaon',
  'Botad',
  'Brahmapur Town',
  'Budaun',
  'Bulandshahr',
  'Bundi',
  'Burari',
  'Burhanpur',
  'Buxar',
  'Champdani',
  'Chandannagar',
  'Chandausi',
  'Chandigarh',
  'Chandrapur',
  'Chapra',
  'Chas',
  'Chennai',
  'Chhattarpur',
  'Chhindwara',
  'Chikmagalur',
  'Chilakaluripet',
  'Chitradurga',
  'Chittaurgarh',
  'Chittoor',
  'Churu',
  'Coimbatore',
  'Cuddalore',
  'Cuttack',
  'Dabgram',
  'Dallo Pura',
  'Daman',
  'Damoh',
  'Darbhanga',
  'Darjiling',
  'Datia',
  'Davanagere',
  'Deesa',
  'Dehradun',
  'Dehri',
  'Delhi',
  'Delhi Cantonment',
  'Deoghar',
  'Deoli',
  'Deoria',
  'Dewas',
  'Dhanbad',
  'Dharmavaram',
  'Dhaulpur',
  'Dhule',
  'Dibrugarh',
  'Dimapur',
  'Dinapur Nizamat',
  'Dindigul',
  'Dum Dum',
  'Durg',
  'Durgapur',
  'Eluru',
  'English Bazar',
  'Erode',
  'Etah',
  'Etawah',
  'Faizabad',
  'Faridabad',
  'Farrukhabad and Fatehgarh',
  'Fatehpur',
  'Firozabad',
  'Firozpur',
  'Gadag and Betigeri',
  'Gandhidham',
  'Gandhinagar',
  'Ganganagar',
  'Gangapur',
  'Gangawati',
  'Gangtok',
  'Gaya',
  'Ghaziabad',
  'Ghazipur',
  'Giridih',
  'Godhra',
  'Gokal Pur',
  'Gonda',
  'Gondal',
  'Gondiya',
  'Gorakhpur',
  'Greater Noida',
  'Gudivada',
  'Gulbarga',
  'Guna',
  'Guntakal',
  'Guntur',
  'Gurgaon',
  'Guwahati',
  'Gwalior',
  'Habra',
  'Hajipur',
  'Haldia',
  'Haldwani and Kathgodam',
  'Halisahar',
  'Hanumangarh',
  'Haora',
  'Hapur',
  'Hardoi',
  'Hardwar',
  'Hassan',
  'Hastsal',
  'Hathras',
  'Hazaribag',
  'Hindaun',
  'Hindupur',
  'Hinganghat',
  'Hisar',
  'Hoshangabad',
  'Hoshiarpur',
  'Hospet',
  'Hosur',
  'Hubli and Dharwad',
  'Hugli and Chinsurah',
  'Hyderabad',
  'Ichalkaranji',
  'Imphal',
  'Indore',
  'Jabalpur',
  'Jagadhri',
  'Jagdalpur',
  'Jaipur',
  'Jalandhar',
  'Jalgaon',
  'Jalna',
  'Jalpaiguri',
  'Jamalpur',
  'Jammu',
  'Jamnagar',
  'Jamshedpur',
  'Jamuria',
  'Jaunpur',
  'Jehanabad',
  'Jetpur Navagadh',
  'Jhansi',
  'Jhunjhunun',
  'Jind',
  'Jodhpur',
  'Junagadh',
  'Kadapa',
  'Kaithal',
  'Kakinada',
  'Kalol',
  'Kalyan and Dombivali',
  'Kalyani',
  'Kamarhati',
  'Kancheepuram',
  'Kanchrapara',
  'Kanpur',
  'Kanpur Cantonment',
  'Kapurthala',
  'Karaikkudi',
  'Karawal Nagar',
  'Karimnagar',
  'Karnal',
  'Kasganj',
  'Kashipur',
  'Katihar',
  'Khammam',
  'Khandwa',
  'Khanna',
  'Kharagpur',
  'Khardaha',
  'Khargone',
  'Khora',
  'Khurja',
  'Kirari Suleman Nagar',
  'Kishanganj',
  'Kishangarh',
  'Kochi',
  'Kolar',
  'Kolhapur',
  'Kolkata',
  'Kollam',
  'Korba',
  'Kota',
  'Kozhikode',
  'Krishnanagar',
  'Kulti',
  'Kumbakonam',
  'Kurichi',
  'Kurnool',
  'Lakhimpur',
  'Lalitpur',
  'Latur',
  'Loni',
  'Lucknow',
  'Ludhiana',
  'Machilipatnam',
  'Madanapalle',
  'Madavaram',
  'Madhyamgram',
  'Madurai',
  'Mahbubnagar',
  'Mahesana',
  'Maheshtala',
  'Mainpuri',
  'Malegaon',
  'Malerkotla',
  'Mandoli',
  'Mandsaur',
  'Mandya',
  'Mangalore',
  'Mango',
  'Mathura',
  'Maunath Bhanjan',
  'Medinipur',
  'Meerut',
  'Mira and Bhayander',
  'Miryalaguda',
  'Mirzapur and Vindhyachal',
  'Modinagar',
  'Moga',
  'Mohali',
  'Moradabad',
  'Morena',
  'Morvi',
  'Motihari',
  'Mughalsarai',
  'Muktsar',
  'Mumbai',
  'Munger',
  'Murwara',
  'Mustafabad',
  'Muzaffarnagar',
  'Muzaffarpur',
  'Mysore',
  'Nabadwip',
  'Nadiad',
  'Nagaon',
  'Nagapattinam',
  'Nagaur',
  'Nagda',
  'Nagercoil',
  'Nagpur',
  'Naihati',
  'Nalgonda',
  'Nanded Waghala',
  'Nandurbar',
  'Nandyal',
  'Nangloi Jat',
  'Narasaraopet',
  'Nashik',
  'Nasik',
  'Navi Mumbai',
  'Navsari',
  'NDMC',
  'Neemuch',
  'Nellore',
  'New Delhi',
  'Neyveli',
  'Nizamabad',
  'Noida',
  'North Barrackpur',
  'North Dum Dum',
  'Ongole',
  'Orai',
  'Osmanabad',
  'Other',
  'Ozhukarai',
  'Palakkad',
  'Palanpur',
  'Palghar',
  'Pali',
  'Pallavaram',
  'Palwal',
  'Panchkula',
  'Panihati',
  'Panipat',
  'Panvel',
  'Parbhani',
  'Patan',
  'Pathankot',
  'Patiala',
  'Patna',
  'Pilibhit',
  'Pimpri and Chinchwad',
  'Pithampur',
  'Porbandar',
  'Port Blair',
  'Proddatur',
  'Puducherry',
  'Pudukkottai',
  'Pune',
  'Puri Town',
  'Purnia',
  'Puruliya',
  'Rae Bareli',
  'Raichur',
  'Raiganj',
  'Raigarh',
  'Raipur',
  'Rajahmundry',
  'Rajapalayam',
  'Rajarhat Gopalpur',
  'Rajkot',
  'Rajnandgaon',
  'Rajpur Sonarpur',
  'Ramagundam',
  'Rampur',
  'Ranchi',
  'Ranibennur',
  'Raniganj',
  'Ratlam',
  'Raurkela',
  'Raurkela Industrial Township',
  'Rewa',
  'Rewari',
  'Rishra',
  'Robertson Pet',
  'Rohtak',
  'Roorkee',
  'Rudrapur',
  'Sagar',
  'Saharanpur',
  'Saharsa',
  'Salem',
  'Sambalpur',
  'Sambhaji Nagar',
  'Sambhal',
  'Sangli Miraj Kupwad',
  'Santipur',
  'Sasaram',
  'Satara',
  'Satna',
  'Sawai Madhopur',
  'Secunderabad',
  'Sehore',
  'Seoni',
  'Serampore',
  'Shahjahanpur',
  'Shamli',
  'Shikohabad',
  'Shillong',
  'Shimla',
  'Shimoga',
  'Shivpuri',
  'Sikar',
  'Silchar',
  'Siliguri',
  'Silvassa',
  'Singrauli',
  'Sirsa',
  'Sitapur',
  'Siwan',
  'Solapur',
  'Sonipat',
  'South Dum Dum',
  'Srikakulam',
  'Srinagar',
  'Sujangarh',
  'Sultan Pur Majra',
  'Sultanpur',
  'Surat',
  'Surendranagar Dudhrej',
  'Suryapet',
  'Tadepalligudem',
  'Tadpatri',
  'Tambaram',
  'Tarapur',
  'Tenali',
  'Thane',
  'Thanesar',
  'Thanjavur',
  'Thiruvananthapuram',
  'Thoothukkudi',
  'Thrissur',
  'Tiruchirappalli',
  'Tirunelveli',
  'Tirupati',
  'Tiruppur',
  'Tiruvannamalai',
  'Tiruvottiyur',
  'Titagarh',
  'Tonk',
  'Tumkur',
  'Udaipur',
  'Udgir',
  'Udupi',
  'Ujjain',
  'Ulhasnagar',
  'Uluberia',
  'Unnao',
  'Uttarpara Kotrung',
  'Vadodara',
  'Valsad',
  'Vapi',
  'Varanasi',
  'Vasai Virar',
  'Vellore',
  'Veraval',
  'Vidisha',
  'Vijayawada',
  'Visakhapatnam',
  'Vizianagaram',
  'Warangal',
  'Wardha',
  'Yamunanagar',
  'Yavatmal',
];

export const QUALIFICATIONS = [
  '10th',
  '12th',
  'ITI',
  'Diploma Engg.',
  'Bachelors Degree',
  'Masters Degree',
  'CA/CS',
  'Other',
];

export const PROGRAMS = [
  { id: 'PhD', name: 'PhD' },
  { id: 'MBA', name: 'MBA' },
  { id: 'BTech', name: 'BTech' },
  { id: 'MCA', name: 'MCA' },
  { id: 'MSc', name: 'MSc' },
  { id: 'MTech', name: 'MTech' }
];

export const SPECIALISATIONS: Record<string, string[]> = {
  'BTech': [
    'Bio-Medical',
    'Bio-Technology',
    'Chemical',
    'Civil',
    'Computer Science',
    'Electrical',
    'Electrical & Electronics',
    'Electronics & Comm.',
    'Fire & Safety',
    'Food Technology',
    'Information Technology',
    'Instrumentation & Control',
    'Leather Technology',
    'Mechanical',
    'Mechatronics',
    'Metallurgical',
    'Mining Technology',
    'Petroleum',
    'Polymer',
    'Production',
    'Textile',
    'Other',
  ],
  'MTech': [
    'Computer Science',
    'Information Technology',
    'Electronics & Comm.',
    'Electrical',
    'Mechanical',
    'Civil',
    'Chemical',
    'Structural Engineering',
    'Power Systems',
    'VLSI Design',
    'Other',
  ],
  'MBA': [
    'Digital Marketing',
    'Disaster Management',
    'E-Commerce',
    'Economics',
    'Fashion Designing',
    'Finance',
    'Healthcare Management',
    'Hospital Management',
    'Hospitality & Tourism',
    'Hotel Management',
    'Human Resource',
    'Information Technology',
    'Insurance & Banking',
    'Interior Designing',
    'International Business',
    'International Relations',
    'Journalism & Electronics Media',
    'Marketing',
    'Production & Operation',
    'Project Management',
    'Public Relations',
    'Retail Management',
    'Rural',
    'Solar & Renewable Energy',
    'Start Up & Entrepreneurship',
    'Supply Chain',
    'Total Quality',
    'Other',
  ],
  'MCA': [
    'Software Development',
    'Data Science',
    'Cyber Security',
    'Cloud Computing',
    'Artificial Intelligence',
    'Other',
  ],
  'BSc': [
    'Biochemistry',
    'Biotechnology',
    'Botany',
    'Chemistry',
    'Environment Science',
    'Geography',
    'Home Science',
    'Hotel Management',
    'Mathematics',
    'Microbiology',
    'MLT',
    'Naturopathy & Yoga',
    'Physics',
    'Psychology',
    'Statistics',
    'Zoology',
    '(General)CBZ',
    '(General)PCB',
    '(General)PCM',
    'Interior Des.',
    'Fashion Des',
    'Other',
  ],
  'MSc': [
    'Biochemistry',
    'Biotechnology',
    'Botany',
    'Chemistry',
    'Environment Science',
    'Geography',
    'Home Science',
    'Hotel Management',
    'Mathematics',
    'Microbiology',
    'MLT',
    'Naturopathy & Yoga',
    'Physics',
    'Psychology',
    'Statistics',
    'Zoology',
    'Interior Des.',
    'Fashion Des',
    'Other',
  ],
  'BA': [
    'Economics',
    'English',
    'Fine Arts',
    'Geography',
    'Hindi',
    'History',
    'Journalism & Mass Comm.',
    'Mathematics',
    'Philosophy',
    'Political Science',
    'Psychology',
    'Public Administration',
    'Sanskrit',
    'Social Work',
    'Sociology',
    'Other',
  ],
  'MA': [
    'Economics',
    'English',
    'Fine Arts',
    'Geography',
    'Hindi',
    'History',
    'Journalism & Mass Comm.',
    'Mathematics',
    'Philosophy',
    'Political Science',
    'Psychology',
    'Public Administration',
    'Sanskrit',
    'Social Work',
    'Sociology',
    'Other',
  ],
  'Diploma Engg.': [
    'Civil',
    'Computer Science',
    'Electrical',
    'Electronics & Comm.',
    'Fire & Safety',
    'Information Technology',
    'Mechanical',
    'Other',
  ],
  'PhD': [],
  'Other': [
    'General',
    'Other',
  ],
  'default': [
    'General',
    'Other',
  ],
};

export const INDIAN_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const EMPLOYMENT_STATUS = [
  'Employed',
  'Unemployed',
  'Self Employed',
  'Freelancer',
  'Student',
  'Retired',
  'Other'
];

export function generateYears(startYear: number = 1970, endYear: number = new Date().getFullYear()): number[] {
  const years: number[] = [];
  for (let year = endYear; year >= startYear; year--) {
    years.push(year);
  }
  return years;
}

export function getAvailableSpecialisations(program: string): string[] {
  if (program === 'PhD') {
    return [];
  }
  return SPECIALISATIONS[program] || SPECIALISATIONS.default;
}
